### ISSUE TITLE
Download openapi on daily cron and commit a "fix: " if it has changed

### ISSUE THREAD

**Issue by seveibar** [seamapi/seam-cli#18]
Github action that runs `npm run download-openapi` and rebuilds the project on cron

Here's an example of a Github action cron that runs daily https://github.com/seamapi/roles/blob/main/.github/workflows/sync.yml

CC @kainpets

**Comment by kainpets** [comment]
@seveibar, do we want to change how openapi spec is generated and worked with? Currently it's installed as a dependency and generated in get-api-definitions.ts. Should I create a script that generates an openapi spec and will replace the dependency?
<img width="1332" alt="Screenshot 2024-02-14 at 12 28 25" src="https://github.com/seamapi/seam-cli/assets/41388251/c9d1ff23-2233-45f0-ab85-a390784caab2">
