### ISSUE TITLE
Seam CLI authorized with PAT fails when calling /client_sessions/create with an `user_identity_ids`

### ISSUE THREAD

**Issue by dawnho** [seamapi/seam-cli#260]
Error returned when using the CLI from the console UI
```
/client_sessions/create
Request Params:
{ user_identity_ids: [ '6d269eb6-abff-4bb5-a5e9-8215e943ab87' ] }


[404]

{
  error: {
    type: 'api_key_not_found',
    message: 'API Key not found',
    request_id: 'c679ea80-7cc8-445a-ba42-d27dc841ac40'
  },
  ok: false
}

```

<img width="987" alt="Screenshot 2024-12-17 at 1 29 49 AM" src="https://github.com/user-attachments/assets/7b99b5c1-94f3-4afe-b247-f67f87a12ceb" />

**Comment by razor-x** [comment]
@dawnho We need some more information look into this issue. The `api_key_not_found` error suggests this issue may not be related to the `/client_sessions/create` endpoint. Can you provide the workspace ID and the api key ID (NOT the actual API key) you are using to make this request?

This request is working when I attempt it

<img width="958" alt="image" src="https://github.com/user-attachments/assets/46f29f09-4ea9-426e-9fb5-77a55a39f349">

**Comment by razor-x** [comment]
@dawnho I confirmed the underlying issue is that this API endpoint needs to be updated to support console sessions

**Comment by dawnho** [comment]
Response:
```
fetch("https://cli.seam.co/api/proxy/client_sessions/create", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIwOTZkNDRjMC1mNTdkLTQ5MjMtOWNhYS01YmNlNTNmMjYxZDAiLCJ1c2VyX2lkIjoiNmQwMTYzMjctZDZkMy00NDExLWI5YzgtMjc0MzY5MGUzNDQ1IiwiaWF0IjoxNzI3OTEyNzk0fQ.wpyn-Oni33xS8HM9f0Oqllx9Yuc4p3c8gIi_3dLCM0U",
    "content-type": "application/json",
    "seam-lts-version": "1.0.0",
    "seam-sdk-name": "seamapi/javascript-http",
    "seam-sdk-version": "0.0.0",
    "seam-workspace": "54877146-4a68-405a-a865-960ce8387bf2"
  },
  "referrer": "",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"user_identity_ids\":[\"ba669be4-ae62-4880-b5bc-0887e9958d12\"]}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by mikewuu** [comment]
@razor-x  console auth is included in https://github.com/seamapi/seam-connect/pull/9525
