### ISSUE TITLE
`seam login`: CLI Error: ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by BadPirate** [seamapi/seam-cli#36]
Attempted installing per [README] instructions on Mac running latest Sonoma, and `seam login` fails after entering PAT token, throwing "fetch is not defined" error:

```
✔ Personal Access Token: … seam_[redacted]
PAT saved! You may not begin using the CLI!
CLI Error: ReferenceError: fetch is not defined
ReferenceError: fetch is not defined
    at n (/Users/badpirate/.nvm/versions/node/v16.17.0/lib/node_modules/seam-cli/node_modules/redaxios/dist/redaxios.js:1:891)
    at Function.n.get (/Users/badpirate/.nvm/versions/node/v16.17.0/lib/node_modules/seam-cli/node_modules/redaxios/dist/redaxios.js:1:1380)
    at /Users/badpirate/.nvm/versions/node/v16.17.0/lib/node_modules/seam-cli/dist/cli.cjs:25937:37
    at Generator.next (<anonymous>)
    at /Users/badpirate/.nvm/versions/node/v16.17.0/lib/node_modules/seam-cli/dist/cli.cjs:62:61
    at new Promise (<anonymous>)
    at __async (/Users/badpirate/.nvm/versions/node/v16.17.0/lib/node_modules/seam-cli/dist/cli.cjs:46:10)
    at interactForWorkspaceId (/Users/badpirate/.nvm/versions/node/v16.17.0/lib/node_modules/seam-cli/dist/cli.cjs:25933:36)
    at /Users/badpirate/.nvm/versions/node/v16.17.0/lib/node_modules/seam-cli/dist/cli.cjs:25969:9
    at Generator.next (<anonymous>)
```

**Comment by BadPirate** [comment]
Update: Even though it shows failed, it does seem to work?

`seam workspaces list` returned good value.

**Comment by razor-x** [comment]
Can you confirm your Node.js version with `node --version`? I believe there are two main ways to use the cli: with an existing node installation via `npm i seam-cli` or using the single binary that bundles the node runtime.

Either way I believe I know what needs to be fixed to remove the decency on fetch which should resolve this issue.

**Comment by razor-x** [comment]
I see it's using node 16 which does not bundle fetch. This should have been polyfilled in the project if Node 16 was supported. Note that Node 16 is now end of life though and major projects and platforms are quickly dropping support.

It looks like you are using nvm, so if you can update to node 18 or 20 I think the error will go away.

**Comment by BadPirate** [comment]
It did. I was on the older one thanks to having to work with another
project that didn't support newer. :)

**Comment by mikewuu** [comment]
Closing this as it was due to unsupported node version (16)
