### ISSUE TITLE
Connect Webview Create -- Redirect to Link

### ISSUE THREAD

**Issue by sybohy** [seamapi/seam-cli#49]
It would be super nice to prompt the user to redirect them in their browser to the connect webview url that gets generated after invoking a create command. Or at least offer to copy the url in the clipboard.

```sh
➜  ~ seam connect-webviews create

✔ [/connect_webviews/create] Parameters › [Make API Call] /connect_webviews/create


/connect_webviews/create
Request Params:
{}


[200]
{
  connect_webview: {
    url: 'https://connect.getseam.com/connect_webviews/view?connect_webview_id=3a966edd-9b46-41c1-a330-b899891b943e&auth_token=CjruEU1FABFwf1ZkpGEeVaUXvN94ugjpE',
    status: 'pending',
```

**Comment by seveibar** [comment]
love it

**Comment by seveibar** [comment]
Implementation note: Recommendation: Use the same flow as an action attempt and ASK the user before you attempt to open their browser

**Comment by seveibar** [comment]
IF we're in a web-browser, indicated by `process.env.INSIDE_WEB_BROWSER=1`, don't show the prompt, we'll add support for the prompt in web browsers later
