### ISSUE TITLE
Add `seam -h` or `seam --help`

### ISSUE THREAD

**Issue by seveibar** [seamapi/seam-cli#5]
It should show all the CLI built-in commands first for example it should show `seam login` etc. There are lots of utility libraries to help with printing help strings e.g. https://www.npmjs.com/package/command-line-usage

**Comment by mastafit** [comment]
![image](https://github.com/seamapi/seam-cli/assets/67077601/2b552466-8603-497d-8916-7d2ae533be0f)
@seveibar What do you think about such implementation?
