### ISSUE TITLE
CLI should allow for toggling config option "always_use_remote_api_defs"

### ISSUE THREAD

**Issue by seveibar** [seamapi/seam-cli#64]
This is primarily for seam developers that always want openapi to be up to date for their CLI.

`--remote-api-defs`

**Comment by mikewuu** [comment]
Heyoo @kainpets, are you working on this one?

**Comment by kainpets** [comment]
Yeah, but kinda stuck on this. I don't think I have made anything meaningful, so feel free to take over or include me in some way.
