### ISSUE TITLE
acs credential metadata isn't displayed

### ISSUE THREAD

**Issue by ethanplee14** [seamapi/seam-cli#93]
![image](https://github.com/seamapi/seam-cli/assets/18000293/986c82aa-67a5-4201-be81-782bd9005e39)

**Comment by mikewuu** [comment]
Closing as appears to be fixed

![CleanShot 2024-03-14 at 19 34 15@2x](https://github.com/seamapi/seam-cli/assets/11449462/cc27762d-5451-4906-920a-0f525abf8047)

![CleanShot 2024-03-14 at 19 33 54@2x](https://github.com/seamapi/seam-cli/assets/11449462/d8e6a2d5-9054-4dec-8f45-9e34b2b001ed)
