### ISSUE TITLE
create release per npm release

### ISSUE THREAD

**Issue by chenrui333** [seamapi/seam-cli#99]
👋 the github release should be technically in sync with npm release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/164183

**Comment by chenrui333** [comment]
still an issue with 0.0.45

![image](https://github.com/seamapi/seam-cli/assets/1580956/510f6c5e-04ee-479a-b12c-bc85dc77278a)

**Comment by seveibar** [comment]
@chenrui333 this is a bug with the auto-publishing setup on our end, we're on it!

**Comment by kainpets** [comment]
> still an issue with 0.0.45
> 
> ![image](https://private-user-images.githubusercontent.com/1580956/308586349-510f6c5e-04ee-479a-b12c-bc85dc77278a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTIwNjYsIm5iZiI6MTcwOTI1MTc2NiwicGF0aCI6Ii8xNTgwOTU2LzMwODU4NjM0OS01MTBmNmM1ZS0wNGVlLTQ3OWEtYjEyYy1iYzg1ZGM3NzI3OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMDAwOTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk0Yzg4NGQyZDFkNTU1ODQzYmUyYWJjYjllZjA0OGZlNmZlYjNiNmY0MWQ1OWU1ZjA2YTdkMzU4NWQ4YWE0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.39CLQCW2-8XmMDK752LMLvA6h-6CK8URtofgUVDxwP0)
> 
> ![image](https://private-user-images.githubusercontent.com/1580956/308586423-8f0c5152-a1e6-439e-b95f-28e63e7a84d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNTIwNjYsIm5iZiI6MTcwOTI1MTc2NiwicGF0aCI6Ii8xNTgwOTU2LzMwODU4NjQyMy04ZjBjNTE1Mi1hMWU2LTQzOWUtYjk1Zi0yOGU2M2U3YTg0ZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMDAwOTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWMwNGM4ZTM2OGVkMzk2ZDAwOTNiMzFkNWQ3ZjJmNmY4ZjA3Y2ZlNzhmZGI0Y2U4YWY5NTgwNjA3ZDMyYjU1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._QDMlNhW4z4ifu7KiQUbApBjjAbvgG7oH1VYVcoCM2w)

@chenrui333, the issue should be resolved now

<img width="961" alt="Screenshot 2024-03-01 at 01 17 45" src="https://github.com/seamapi/seam-cli/assets/41388251/60518290-80c2-4273-9c50-2628d5277941">

<img width="275" alt="Screenshot 2024-03-01 at 01 19 00" src="https://github.com/seamapi/seam-cli/assets/41388251/f7806d24-4e9c-4c8c-a974-27ac203289a2">

**Comment by kainpets** [comment]
https://github.com/Homebrew/homebrew-core/pull/164183
